# Generated by Django 5.1.4 on 2024-12-13 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('date_create_buyer', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kind', models.CharField(max_length=50, verbose_name='Название вида')),
                ('specification_kind', models.TextField(verbose_name='Описание вида')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='Название категории')),
                ('specification_category', models.TextField(verbose_name='Описание категории')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seeds.kind', verbose_name='Вид растения')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=50, verbose_name='Название сорта')),
                ('specification_product', models.TextField(verbose_name='Описание сорта')),
                ('amount', models.PositiveSmallIntegerField(verbose_name='Количество в упаковке')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Цена')),
                ('balance', models.PositiveIntegerField(verbose_name='Остаток')),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='seeds.category', verbose_name='Категория')),
                ('kind', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='seeds.kind', verbose_name='Вид растения')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_buyer', models.CharField(max_length=100, verbose_name='Получатель')),
                ('address_buyer', models.CharField(max_length=300, verbose_name='Адрес получателя')),
                ('amount_order', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость заказа')),
                ('date_create_order', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('active_order', models.BooleanField(default=True, verbose_name='Заказ активный?')),
                ('text_order', models.TextField(verbose_name='Примечание')),
                ('author_order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seeds.buyer', verbose_name='Автор заказа')),
                ('list_product', models.ManyToManyField(related_name='Заказы', to='seeds.product')),
            ],
        ),
    ]
