# Generated by Django 5.1.4 on 2024-12-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabricator',
            field=models.CharField(default='sss', max_length=50, verbose_name='Производитель'),
            preserve_default=False,
        ),
    ]
