# Generated by Django 5.1.4 on 2024-12-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0003_remove_product_kind_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='text_order',
            field=models.TextField(default=None, verbose_name='Примечание'),
        ),
    ]
